package org.firstinspires.ftc.teamcode.drive;

public enum ATRobotMode {
    AUTO_RED_RIGHT_MEDIUM_SETUP,
    AUTO_RED_RIGHT_MEDIUM_PICK_CONE,
    AUTO_RED_RIGHT_MEDIUM_PARK,
    AUTO_RED_RIGHT_HIGH_SETUP,
    AUTO_RED_RIGHT_HIGH_PICK_CONE,
    AUTO_RED_RIGHT_LOW,
    MANUAL,
    RESET,
    STOP,
    AUTO ,
    PARK1 ,
    PARK2 ,
    PARK3 ,
    SUBSTATION ,
    MANUAL_RIGHT_PICKUP,
    MANUAL_LEFT_PICKUP,
    MANUAL_HIGH_DROP,
    MANUAL_MEDIUM_DROP,
    MANUAL_LOW_DROP,
    TERMINAL
}
